# Generated by Django 2.2.3 on 2019-07-13 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('subtitle', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('book_format', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('loc_class', models.CharField(max_length=100)),
                ('loc_ctrl', models.CharField(max_length=100)),
                ('dewey', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=150)),
                ('lang', models.CharField(max_length=30)),
                ('book_status', models.CharField(max_length=50)),
                ('cover', models.FileField(upload_to='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(related_name='subjects', to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(related_name='genres', to='books.Book')),
            ],
        ),
    ]
